version: "2"

run:
  timeout: 5m
  tests: true

linters:  
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gocritic
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      disable-default-exclusions: false
    govet:
      enable:
        - shadow
  exclusions:
    warn-unused: false
    presets:
      - comments
      - common-false-positives
      - std-error-handling
      - legacy
    paths:
      - ".*_test\\.go"
      - ".*/go/.*"
      - ".*/usr/local/go/.*"
      - ".*/runtime/.*"
      - vendor
      - tmp
      - go
      - runtime
  

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats: 
    text:
      colors: true
      print-issued-lines: true
      print-linter-name: true

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/undersleep7x/cryo-project
  