version: "3.8"

services:
  app:
    build: .
    container_name: cryowallet-app
    working_dir: /app/cmd
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - APP_ENV=local
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["air"]
  
  redis:
    image: redis:7.0-alpine
    container_name: cryowallet-redis
    ports:
      - "6379:6379"