name: Status Checks  # Workflow name

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    strategy:
      matrix:
        task: [test, lint]  # Runs both tests and linting in parallel

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx (for advanced builds)
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t cryowallet-dev .

      - name: Run Linter in Docker
        if: matrix.task == 'lint'
        run: |
          docker run --rm \
            --env ENV=test \
            cryowallet-dev \
            golangci-lint run ./...

      - name: Run Tests in Docker
        if: matrix.task == 'test'
        run: |
          docker run --rm \
            --env ENV=test \
            -v ${{ github.workspace }}:/app \
            cryowallet-dev \
            sh -c "go test -coverprofile=coverage.out ./..."

      - name: Check Test Coverage (Optional)
        run: |
          cat coverage.out

      - name: Enforce Test Coverage >= 80%
        run: |
          coverage=$(go tool cover -func=coverage.out | grep total: | awk '{print substr($3, 1, length($3)-1)}')
          echo "Total Coverage: $coverage%"
          if (( $(echo "$coverage < 80.0" | bc -l) )); then
            echo "Test coverage below 80% threshold"
            exit 1
          fi


