name: Status Checks  # Workflow name

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go (Force Correct Version)
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Verify Go Version  # Debugging step
        run: go version  # Should print "go1.20 linux/amd64"

      - name: Enable Go Modules
        run: echo "GO111MODULE=on" >> $GITHUB_ENV

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Tests
        run: go test ./...

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go (Force Correct Version)
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Verify Go Version  # Debugging step
        run: go version  # Should print "go1.20 linux/amd64"

      - name: Enable Go Modules
        run: echo "GO111MODULE=on" >> $GITHUB_ENV

      - name: Install GolangCI-Lint
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin  # Ensure GOPATH is set
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH
          golangci-lint --version  # Debugging step to check if it installed

      - name: Run Linter
        run: golangci-lint run ./...
